In [78]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
from docx import Document
from docx.shared import Inches

decode_lab_internship = pd.read_excel(r"C:\Users\ThePhantomTrader\OneDrive\Desktop\DECODE LABS\Dataset for Data Analytics.xlsx")
output_dir = Path(r"C:\Users\ThePhantomTrader\OneDrive\Desktop\DECODE LABS\Week_1_files")
output_dir.mkdir(exist_ok=True)
decode_lab_internship

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [79]:
decode_lab_internship.info

<bound method DataFrame.info of         OrderID       Date CustomerID  Product  Quantity  UnitPrice  \
0     ORD200000 2023-01-04     C72649  Monitor         5     570.62
1     ORD200001 2024-08-23     C75739    Phone         2     151.35
2     ORD200002 2024-02-27     C81728   Tablet         5     550.68
3     ORD200003 2023-10-15     C33540    Chair         1     273.19
4     ORD200004 2025-05-08     C81840  Printer         4     626.01
...         ...        ...        ...      ...       ...        ...
1195  ORD201195 2024-06-20     C21126     Desk         1     107.04
1196  ORD201196 2024-03-04     C20095  Monitor         2     662.53
1197  ORD201197 2023-07-13     C79674   Tablet         2     436.84
1198  ORD201198 2024-08-22     C64753    Chair         4     262.52
1199  ORD201199 2023-06-11     C57502   Tablet         4     560.58

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0        928 Main St    Debit Card     Shipped    TRK37947903            7
1        823 Main St        Online     Shipped    TRK91186779            3
2        512 Main St   Credit Card   Cancelled    TRK42903982            8
3        275 Main St    Debit Card    Returned    TRK62788070            5
4        668 Main St        Online   Delivered    TRK29241424            8
...              ...           ...         ...            ...          ...
1195     392 Main St   Credit Card   Cancelled    TRK38009181            6
1196     778 Main St        Online   Cancelled    TRK69207593            5
1197     275 Main St        Online   Delivered    TRK88039356            2
1198     509 Main St    Debit Card   Cancelled    TRK71683331            4
1199     201 Main St     Gift Card    Returned    TRK51116746            6

     CouponCode ReferralSource  TotalPrice
0        SAVE10      Instagram     2853.10
1        SAVE10       Referral      302.70
2      FREESHIP          Email     2753.40
3        SAVE10       Facebook      273.19
4        SAVE10          Email     2504.04
...         ...            ...         ...
1195   FREESHIP         Google      107.04
1196        NaN       Facebook     1325.06
1197   FREESHIP      Instagram      873.68
1198   WINTER15      Instagram     1050.08
1199     SAVE10       Referral     2242.32

[1200 rows x 14 columns]>

In [80]:

decode_lab_internship.dtypes

OrderID                       str
Date               datetime64[us]
CustomerID                    str
Product                       str
Quantity                    int64
UnitPrice                 float64
ShippingAddress               str
PaymentMethod                 str
OrderStatus                   str
TrackingNumber                str
ItemsInCart                 int64
CouponCode                    str
ReferralSource                str
TotalPrice                float64
dtype: object

In [81]:
decode_lab_internship.shape

(1200, 14)

In [82]:
decode_lab_internship.describe

<bound method NDFrame.describe of         OrderID       Date CustomerID  Product  Quantity  UnitPrice  \
0     ORD200000 2023-01-04     C72649  Monitor         5     570.62
1     ORD200001 2024-08-23     C75739    Phone         2     151.35
2     ORD200002 2024-02-27     C81728   Tablet         5     550.68
3     ORD200003 2023-10-15     C33540    Chair         1     273.19
4     ORD200004 2025-05-08     C81840  Printer         4     626.01
...         ...        ...        ...      ...       ...        ...
1195  ORD201195 2024-06-20     C21126     Desk         1     107.04
1196  ORD201196 2024-03-04     C20095  Monitor         2     662.53
1197  ORD201197 2023-07-13     C79674   Tablet         2     436.84
1198  ORD201198 2024-08-22     C64753    Chair         4     262.52
1199  ORD201199 2023-06-11     C57502   Tablet         4     560.58

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0        928 Main St    Debit Card     Shipped    TRK37947903            7
1        823 Main St        Online     Shipped    TRK91186779            3
2        512 Main St   Credit Card   Cancelled    TRK42903982            8
3        275 Main St    Debit Card    Returned    TRK62788070            5
4        668 Main St        Online   Delivered    TRK29241424            8
...              ...           ...         ...            ...          ...
1195     392 Main St   Credit Card   Cancelled    TRK38009181            6
1196     778 Main St        Online   Cancelled    TRK69207593            5
1197     275 Main St        Online   Delivered    TRK88039356            2
1198     509 Main St    Debit Card   Cancelled    TRK71683331            4
1199     201 Main St     Gift Card    Returned    TRK51116746            6

     CouponCode ReferralSource  TotalPrice
0        SAVE10      Instagram     2853.10
1        SAVE10       Referral      302.70
2      FREESHIP          Email     2753.40
3        SAVE10       Facebook      273.19
4        SAVE10          Email     2504.04
...         ...            ...         ...
1195   FREESHIP         Google      107.04
1196        NaN       Facebook     1325.06
1197   FREESHIP      Instagram      873.68
1198   WINTER15      Instagram     1050.08
1199     SAVE10       Referral     2242.32

[1200 rows x 14 columns]>

In [83]:
decode_lab_internship.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='str')

In [84]:
decode_lab_internship.index

RangeIndex(start=0, stop=1200, step=1)

In [85]:
decode_lab_internship = pd.read_excel(r"C:\Users\ThePhantomTrader\OneDrive\Desktop\DECODE LABS\Dataset for Data Analytics.xlsx")
output_dir = Path(r"C:\Users\ThePhantomTrader\OneDrive\Desktop\DECODE LABS\Week_1_files")
output_dir.mkdir(exist_ok=True)

In [86]:
decode_lab_internship.columns = [str(col).strip().replace(" ", "_") for col in decode_lab_internship.columns]
dataset_shape = decode_lab_internship.shape
data_types = decode_lab_internship.dtypes.astype(str)
missing_values = decode_lab_internship.isnull().sum()
missing_values

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [87]:
#To clean the given data
duplicates_before = decode_lab_internship.duplicated().sum()
decode_lab_internship = decode_lab_internship.drop_duplicates()

In [88]:
#  Filling the missing values and converting the date columns
for col in decode_lab_internship.columns:
    if col == "CouponCode":
        decode_lab_internship[col] = decode_lab_internship[col].fillna(
            decode_lab_internship[col].mode()[0])

    if decode_lab_internship[col].dtype == "object":
        decode_lab_internship[col] = decode_lab_internship[col].fillna("Unknown")
    elif decode_lab_internship[col].dtype in ["int64", "float64"]:decode_lab_internship[col] = decode_lab_internship[col].fillna(decode_lab_internship[col].median())

duplicates_after = decode_lab_internship.duplicated().sum()

for col in decode_lab_internship.columns:
    if "date" in col.lower():
        try:decode_lab_internship[col] = pd.to_datetime(decode_lab_internship[col]) 
        except:
            pass
decode_lab_internship

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,FREESHIP,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [89]:
numeric_cols = decode_lab_internship.select_dtypes(include="number").columns

basic_stats = decode_lab_internship[numeric_cols].describe()

analysis_summary = []

for col in numeric_cols:analysis_summary.append(f"{col}: mean={decode_lab_internship[col].mean():.2f}, max={decode_lab_internship[col].max()}, min={decode_lab_internship[col].min()}")
analysis_summary

['Quantity: mean=2.95, max=5, min=1',
 'UnitPrice: mean=356.41, max=699.93, min=11.39',
 'ItemsInCart: mean=5.49, max=10, min=1',
 'TotalPrice: mean=1053.97, max=3456.4, min=11.39']

In [90]:
#To get the outliers
outlier_results = {}

for col in numeric_cols:
    Q1 = decode_lab_internship[col].quantile(0.25)
    Q3 = decode_lab_internship[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = decode_lab_internship[(decode_lab_internship[col] < lower) | (decode_lab_internship[col] > upper)]

    outlier_results[col] = len(outliers)
    outlier_results

In [91]:
#Visualizing 
chart_paths = []
if len(numeric_cols) > 0:
    plt.figure(figsize=(6,4))
    decode_lab_internship[numeric_cols[0]].hist(bins=20)
    plt.title(f"Distribution of {numeric_cols[0]}")
    plt.xlabel(numeric_cols[0])
    plt.ylabel("Frequency")
    hist_path = output_dir / "histogram.png"
    plt.savefig(hist_path, bbox_inches='tight')
    plt.close()
    chart_paths.append(hist_path)

# Correlation heatmap alternative using pandas plotting
if len(numeric_cols) > 1:
    corr = decode_lab_internship[numeric_cols].corr()

    plt.figure(figsize=(8,6))
    plt.imshow(corr, aspect='auto')
    plt.colorbar()
    plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), corr.columns)
    plt.title("Correlation Matrix")
    corr_path = output_dir / "correlation_matrix.png"
    plt.savefig(corr_path, bbox_inches='tight')
    plt.close()
    chart_paths.append(corr_path)

# Bar chart for object column
object_cols = decode_lab_internship.select_dtypes(include="object").columns

if len(object_cols) > 0:
    top_values = decode_lab_internship[object_cols[0]].value_counts().head(10)

    plt.figure(figsize=(7,4))
    top_values.plot(kind='bar')
    plt.title(f"Top Categories in {object_cols[0]}")
    plt.ylabel("Count")
    plt.xticks(rotation=45)
    bar_path = output_dir / "bar_chart.png"
    plt.savefig(bar_path, bbox_inches='tight')
    plt.close()
    chart_paths.append(bar_path)
    chart_paths

C:\Users\ThePhantomTrader\AppData\Local\Temp\ipykernel_25360\1038547540.py:30: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = decode_lab_internship.select_dtypes(include="object").columns

In [92]:
decode_lab_internship

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,FREESHIP,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [93]:
#To predict model
model_results = "Not enough numeric columns for prediction."

if len(numeric_cols) >= 2:
    target = "TotalPrice"
    features = [col for col in numeric_cols if col != target]

    X = decode_lab_internship[features]
    y = decode_lab_internship[target]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42)

    model = LinearRegression()
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    mae = mean_absolute_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)

    model_results = f"""
Target Variable: {target}
Features Used: {', '.join(features)}

Mean Absolute Error: {mae:.2f}
R2 Score: {r2:.2f}
Insight:
The model predicts the target variable using available numeric features.
Higher R2 values indicate stronger predictive performance."""